/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: nolanfa (https://sketchfab.com/nolanfa)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/otter-827aecf5bb4f456cb6d7ac5caf8d6344
Title: Otter
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

import scene from '../assets/3D/otter.glb'

const Otter = ({ currentAnimation, ...props }) => {
    const group = useRef();
    const { nodes, materials, animations } = useGLTF(scene);
    const { actions } = useAnimations(animations, group);


    useEffect(() => {
        Object.values(actions).forEach((action) => action.stop())

        if (actions[currentAnimation]) {
            actions[currentAnimation].play()
        }
    }, [actions, currentAnimation])


    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Sketchfab_Scene">
                <group
                    name="Sketchfab_model"
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={0.082}
                >
                    <group name="Root">
                        <group
                            name="Lamp"
                            position={[4.076, 1.005, 5.904]}
                            rotation={[-0.268, 0.602, 1.931]}
                        >
                            <group name="Lamp_1" />
                        </group>
                        <group name="Armature" position={[0.012, 0.398, 1.436]}>
                            <primitive object={nodes.Armature_rootJoint} />
                            <skinnedMesh
                                name="Cube_0"
                                geometry={nodes.Cube_0.geometry}
                                material={materials.brawn}
                                skeleton={nodes.Cube_0.skeleton}
                            />
                            <skinnedMesh
                                name="Cube_1"
                                geometry={nodes.Cube_1.geometry}
                                material={materials.material}
                                skeleton={nodes.Cube_1.skeleton}
                            />
                            <skinnedMesh
                                name="Cube_2"
                                geometry={nodes.Cube_2.geometry}
                                material={materials.white}
                                skeleton={nodes.Cube_2.skeleton}
                            />
                            <group name="Cube" position={[-0.012, -0.398, -1.436]} />
                        </group>
                    </group>
                </group>
            </group>
        </group>
    );
}

export default Otter
